// Copyright Josh Komoroske. All rights reserved.
// Use of this source code is governed by the MIT license,
// a copy of which can be found in the LICENSE.txt file.

package analytics

import (
	"io"
	"log"
	"net/http"
	"net/http/httptest"
	"net/url"

	"github.com/gofrs/uuid"
)

// Compile-time assertion that Tracker implements http.Handler.
var _ http.Handler = (*Tracker)(nil)

type Tracker struct {
	// TrackingID is the tracking id for the Google Analytics property that you
	// want to track pageview events for. This value can be found in your
	// Google Analytics dashboard.
	// Example: "UA-123456789-1"
	TrackingID string

	// PropertyName is the name for the Google Analytics property that you want
	// to track pageview events for. This can be found in your Google Analytics
	// dashboard.
	// Example: "example.com"
	PropertyName string

	// Handler is a http handler that is "wrapped" by the Tracker and actually
	// processes the client requests. The original request, as well as the
	// response generated by the handler is used to extract analytics data.
	Handler http.Handler
}

func (t *Tracker) ServeHTTP(writer http.ResponseWriter, request *http.Request) {
	// We're going to be leveraging the httptest.ResponseRecorder so that the
	// responses from the wrapped handler can be extracted and copied.
	recorder := httptest.NewRecorder()

	// Execute the wrapped handler so that it writes a response to the recorder.
	t.Handler.ServeHTTP(recorder, request)
	log.Printf("%d %s %v", recorder.Code, request.Method, request.URL)

	// Copy all recorded response properties back to the original response.
	defer func() {
		// Copy all headers.
		for key, values := range recorder.Header() {
			for _, value := range values {
				writer.Header().Add(key, value)
			}
		}
		// Copy status code.
		writer.WriteHeader(recorder.Code)
		// Copy response body.
		io.Copy(writer, recorder.Body)
	}()

	// Set values for the various Google Analytics request query parameters.
	// These values are used to accurately track the pageview event.
	// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters
	params := url.Values{
		// Set "Protocol Version".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#v
		"v": {"1"},

		// Set "Tracking ID/ Web Property ID".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#tid
		"tid": {t.TrackingID},

		// Set "Client ID".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#cid
		"cid": {uuid.Must(uuid.NewV4()).String()},

		// Set "User Agent Override".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ua
		"ua": {request.UserAgent()},

		// Set "Hit type".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#t
		"t": {"pageview"},

		// Set "Non-Interaction Hit".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#ni
		"ni": {"1"},

		// Set "Document Host Name".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dh
		"dh": {t.PropertyName},

		// Set "Document Path".
		// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#dp
		"dp": {request.URL.RequestURI()},
	}

	// Build the Google Analytics collection url.
	// See: https://developers.google.com/analytics/devguides/collection/protocol/v1/reference#endpoint
	googleAnalytics := url.URL{
		Scheme:   "https",
		Host:     "www.google-analytics.com",
		Path:     "collect",
		RawQuery: params.Encode(),
	}

	// Execute the actual request to Google Analytics. We completely ignore the
	// response as the endpoint always returns a successful (200) response,
	// regardless of the request. We also only log an error in order to not
	// interrupt responses back to the client.
	if _, err := http.DefaultClient.Get(googleAnalytics.String()); err != nil {
		log.Printf("error: %v", err)
	}
}
